### PR TITLE
Feat/webworker support rebased

### PR DESCRIPTION
**Pull request by jeswr**
@rubensworks as discussed, pretty well same result as https://github.com/rubensworks/solid-client-authn-js/pull/2 but now containing your original commits.

### CODE REVIEW

**Comment by rubensworks** [comment]
@jeswr I seem to be getting the following error after running `npm install`:

```
lerna notice cli v4.0.0
lerna info ci enabled
lerna info Bootstrapping 5 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 1 in 'e2e-browser'
lerna ERR! npm ci stderr:
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rtaelman/.npm/_logs/2022-07-15T11_38_25_534Z-debug.log
lerna ERR! npm ci exited 1 in 'e2e-browser'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@0.0.0 postinstall: `lerna bootstrap --ci && npm run build`
npm ERR! Exit status 1
```

Are you also getting this error on your system?
Seems to be an issue with the lockfiles not being present in the e2e packages.
Perhaps they got lost during the rebase?

**Comment by rubensworks** [comment]
With your latest commit, it's failing here with
```
> @rubensworks/oidc-client-ext@1.12.1 build /Users/rtaelman/Documents/UGent/nosync/inrupt/solid-client-authn-js/packages/oidc
> rollup --config rollup.config.js

lerna ERR! npm run build stderr:

./src/index.ts → dist/index.js, dist/index.es.js, umd...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@inrupt/oidc-client (imported by src/index.ts)
[!] (plugin rpt2) Error: /Users/rtaelman/Documents/UGent/nosync/inrupt/solid-client-authn-js/packages/oidc/src/dpop/tokenExchange.ts(33,8): semantic error TS2307: Cannot find module '@rubensworks/solid-client-authn-core' or its corresponding type declarations.
src/dpop/tokenExchange.ts
Error: /Users/rtaelman/Documents/UGent/nosync/inrupt/solid-client-authn-js/packages/oidc/src/dpop/tokenExchange.ts(33,8): semantic error TS2307: Cannot find module '@rubensworks/solid-client-authn-core' or its corresponding type declarations.
    at error (/Users/rtaelman/Documents/UGent/nosync/inrupt/solid-client-authn-js/node_modules/rollup/dist/shared/rollup.js:198:30)
```

Does this also occur on your end?

**Comment by jeswr** [comment]
Should be resolved now @rubensworks - lerna wasn't liking the relative file imports

**Comment by rubensworks** [comment]
Thanks! Released as 1.13.0.

**Pull request merged**
